### ISSUE TITLE
error on Import Documentation 

### ISSUE THREAD

**Issue by gallak** [tbellembois/gochimitheque#20]
The command line for importing v1 data in documentation section is incorrect .

wrong : /path/to/gochimitheque -proxyurl=https://appserver.foo.fr -importfrom=/path/to/csv
good :  /path/to/gochimitheque -proxyurl=https://appserver.foo.fr -import**v1**from=/path/to/csv

**Comment by tbellembois** [comment]
Thanks, fixed.
