### ISSUE TITLE
mail for resetting password considered as spam

### ISSUE THREAD

**Issue by gallak** [tbellembois/gochimitheque#21]
I try to generate a token for resetting my password.
The mail was block due to an high spam score  : 

`Nov  5 12:59:22 smtp-server amavis[26774]: (26774-20) Blocked SPAM {BouncedOutbound,Quarantined}, LOCAL [10.10.10.10]:47924 <no-reply-chimitheque@company.fr> -> <gallak@company.fr>, quarantine: U/spam-UcMnm1y52fid.gz, Queue-ID: 162F88261A, mail_id: UcMnm1y52fid, Hits: 7.045, size: 564, 331 ms
`

reason : 
```
X-Quarantine-ID: <UcMnm1y52fid>
X-Amavis-Alert: BAD HEADER SECTION, Missing required header field: "Date"
```

**Comment by tbellembois** [comment]
Thanks for reporting.

**Comment by tbellembois** [comment]
Could you please test with the following version:
https://drive.uca.fr/f/f3263f89d7f6467bb4bc/?dl=1

**Comment by gallak** [comment]
test successfully with this version, I could get a new password.
thanks
