### ISSUE TITLE
Single Sign On ?

### ISSUE THREAD

**Issue by gallak** [tbellembois/gochimitheque#22]
Is the a a way to integrate chimitheque with an SSO like CAS ( Centralized Authentification System) or HTTP-AUTH trough headers with attributes submission.

I could test if necessary

**Comment by tbellembois** [comment]
It is a planned feature. I don't know yet if I will integrate this directly into the application or let an HTTP proxy manage the authentication and just handle the HTTP esponse.

**Comment by gallak** [comment]
IMHO : by managing SSO in my research center and with an web server in front of  of Chimitheque, I thinks it's better to let the an HTTP  proxy manage the authentification and handle the response..
There is a lot of HTTP auth module : CAS / SAML / RADIUS .....

**Comment by tbellembois** [comment]
Yes that sounds easier and more "KISS principle".

**Comment by tbellembois** [comment]
Je mets un morceau de nos échanges par mail pour info.

une personne authentifiée ( le compte se crée si non existant) permettra l'envoi par le mandataire ( serveur CAS / SAML)  de différents attributs : mail, nom affiche , attribut de role

si il n'y a pas d'attribut de role, l'affectation des roles se fera par le gestionnaire principale (après notification) , par le biais d'import d'identifiant ou a la main.

Je rejoins Loïc sur les rôles par défauts proposé :

-----8<-----8<-----8<-----8<

Concernant les droits, on envisager par défaut :
- Product : view
- Restricted products : no permission
- Storage : no permission

-----8<-----8<-----8<-----8<

Si il y a un attribut de rôle, il faudra prévoir un mapping entre les attributs retournés par le mandataire et ceux présent dans chimithèque ( je ne me souvient plus si un rôle peut restreindre l’accès à 1 ou plusieurs entrepôt) alors c'est Chimithèque qui affecte automatiquement la personne dans le bon role ( et notifie le responsable)

cette vérification d'affectation se fait à chaque connexion , ce qui permet de ré affectation la personne aux bons rôles en cas de changement (de rôle)

Note les affectation de rôle par rapport à la personne sont généralement des choses communes sur les système SSO.


Par Exemple

agallavardin se connecte pour la première fois à la chimithèque et le CAS envoie les infos suivantes

    uid : agallavardin
    cn : Antoine Gallavardin
    mail : antoine.gallavardin@inrae.fr
    role : [ CHIMITHEQUE_ROLE1, CHIMITHEQUE_ROLE3, SHAREPOINT_ADMIN]

actions coté gochimitheque

    gochimitheque ne le trouve pas, il le crée avec les infos donnés
    gochimitheque regarde si les roles donnés correspond a un rôle interne
    gochimitheque à le mapping :
        CHIMITHEQUE_ROLE1 : "gestionaire du depot des acides"
        CHIMITHEQUE_ROLE3 : "utilisateur des produits mutagénes"
    gochimitheque affecte a agallavardi , le droit de gérer les depot des acide et d'utiliser les produit mutagéne ( et pas de les administrer)
    gochimitheque n'a pas d'equivalence de role pour "SHAREPOINT_ADMIN", il n'est dons pas traité
    Si gochimitheque a des affectations faite manuellement par l'admin chitmithèque sur le compte agallavardi, ces affectations sont conservées.


Cela reviendrai à développer

    modules d'analyse des entêtes HTTP  ( le plugin apache pour CAS / shibboleth / openidc s'occupe d'envoyer à Gochimi via les entêtes les informations, je peux fournis des confs associés )
    module de création de compte
    module de calcul des affectations et d'alerte en cas de changement
    adapté le système de rôle pour mettre un attribut d’équivalence


Sur l'écran ça parait simple évidement ... mais on peut aider !

Antoine

[1] https://services.renater.fr/documentation/supann/supann2018/recommandations2018/modele/classes#supannperson

**Comment by tbellembois** [comment]
Je clos cette issue car je vais partir vers une authentification OpenID.
Avec une solution comme https://www.keycloak.org/ il sera possible de configurer en backend du CAS, du LDAP ou tout autre provider d'identité. L'idée est de déléguer complètement la gestion des utilisateurs et de simplifier le développement.
