### ISSUE TITLE
history not imported when migrate from v1 to v2

### ISSUE THREAD

**Issue by gallak** [tbellembois/gochimitheque#27]
hello
import work successfully, CAS seems to be correct.
it seems that history of actual and old store ( stock?) aren't importe when migrate data from V1 to v2
history could be important in case of traceability ( quality assurance) of toxuic product and so on .

**Comment by tbellembois** [comment]
Yes, this is an expected behavior. I will add this in the README. No sure I will have time to implement this soon.. I keep the issue opened.

**Comment by tbellembois** [comment]
Added in the documentation.
