### ISSUE TITLE
Installation chimietheque

### ISSUE THREAD

**Issue by nicolasgoudard** [tbellembois/gochimitheque#3]
Merci pour ce  logiciel très convivial 
J’ai pu installer la chimietheque.  Je voudrais vous proposer quelques modifications à la documentation d’installation

- Il est indiqué "You need a Linux AMD64 machine. No dependencies are required."
Le projet ne fonctionne pas sous la dernier version de  CentOS  7. : il dépend de  Glibc2.28  qui ne peut pas s’installer faclement (en tout cas je n’ai pas réussi ) .  
Par contre il fonctionne dès l’installation  sous Debian 10.  Il faudrait suggérer d’installer une Debian 10

- au début de la doc il est indiqué que le compte admin par défaut est  :  admin@chimitheque.com (COM) . Le compte est  admin@chimitheque.fr   (FR). qui est  indiqué à la fin

Pour le mode « production » : 

- le fichier    présent dans doc/apache2-chimitheque.conf  n’est pas un fichier de conf apache2 comme c’est iindiqué, c’est en fait un fichier de configuration pour  Nginx  . Il faut donc installer Nginx sur Debian.   Mettre le fichier de conf dans   /etc/nginx/sites-available et l’activer avec :   ln - s /etc/nginx/sites-available/apache2-chimitheque.conf  /etc/nginx/sites-enabled/

- Dans l'exemple indiqué "gochimitheque -proxyurl https://appserver.foo.fr -proxypath=/chimitheque -admins=john.bar@foo.fr,jean.dupont@foo.fr --mailserveraddress smtp.foo.fr --mailserverport 25 --mailserversender noreply@foo.fr  « 

Le chemin. proxypath=/chimitheque  doit se terminer par un slash proxypath=/chimitheque/    pour être concaténé correctement dans le navigateur.  
La commande  gochimietheque ne se lance pas  si les adresses mails indiqué dans l’option « -admins » ne sont pas dans la base 

- S’il on met une erreur (comme des mails inexistants) dans la commande gochimitheque dans l’option ExectStart dans le fichier chimitheque.service, cela ne produit pas d’erreur de sortie quand on  démarre le service  chimitheque.service  . On pense donc que ça tourne et il faut vérifier que le statut du service pour comprendre  que le service ne tourne pas.  

Merci encore

**Comment by tbellembois** [comment]
Merci pour ce retour détaillé. Je fais les corrections nécessaires.
