### ISSUE TITLE
add a scan link to allow scan qrcode from webcam

### ISSUE THREAD

**Issue by gallak** [tbellembois/gochimitheque#33]
it could useful to add a option to tthe command line like : 
```
root@gochim:/usr/local/chimitheque# /usr/local/chimitheque/gochimitheque  ..... 
-scan-url=http://srv/qr-code
```

Where `http://srv/qr-code` is a tool to flash the qrcode ( like : https://www.the-qrcode-generator.com/scan)  but I tested successfully with https://github.com/jeromeetienne/qrcode-reader/blob/master/README.md  ( I could provide installation instructions)

This option add an icon like " Scan QR" next to "My bookmark" 

It allows scientist to get product directly.

**Comment by tbellembois** [comment]
May be I could offer this feature (QRcode scanning) directly in Chimithèque ?
