### ISSUE TITLE
IE compatibility

### ISSUE THREAD

**Issue by Bismuth69** [tbellembois/gochimitheque#35]
Using Internet Explorer 11: when I log in as an admin or user account, I don't have access to the entire menu, just "password change" and "logout".

screenshot : 
https://image.noelshack.com/fichiers/2019/49/2/1575376527-ie-chimitheque.png

**Comment by tbellembois** [comment]
Hello,
Yes this is expected. I have forgotten to mention this on the README. Please use another web browser (Firefox or Chromium). Sorry but I will never work on the compatibility with Internet Explorer.
