### ISSUE TITLE
user not affiliated with an entity

### ISSUE THREAD

**Issue by Bismuth69** [tbellembois/gochimitheque#37]
When a user is not affiliated to an entity, it is no longer possible to edit his rights, even with the admin account.
example with the account "visiteur@admin.fr" :
[https://www.zupimages.net/up/19/50/z7hs.png](url)

**Comment by tbellembois** [comment]
Could you please test with this version:
https://drive.uca.fr/f/f3263f89d7f6467bb4bc/?dl=1
