### ISSUE TITLE
UI bug : incorrect date

### ISSUE THREAD

**Issue by gallak** [tbellembois/gochimitheque#47]
When editing a product on storage view, we didn't see any date ( entry date, exit date ..)
![image](https://user-images.githubusercontent.com/17747269/84252991-a20f6b00-ab0f-11ea-81e3-177ab9cf8168.png)

But when we export id we saw the date (until we didn't save it in UI)à

Thoses product has been imported from 0.3 version.

Is there a date conversion issue when importing ?

CSV dump form Postgres was like : "2014-07-03 09:15:53"

When export from v2 : it's like : 

creation_date | modification_date | entry_date
-- | -- | --
14 May 20 14:18 +0200 | 10 Jun 20 11:35 +0200 | 12 Feb 18 14:49 UTC

**Comment by gallak** [comment]
maybe its not a bug because we see the correct dqte whe clickling in the "+" sign like : 
![image](https://user-images.githubusercontent.com/17747269/84256129-d38a3580-ab13-11ea-95d2-dd3081b65ad8.png)

anyway, in the previous version when we edit an product we saw this initial value.

**Comment by gallak** [comment]
import done twice, same effect, no previous date inside form

**Comment by tbellembois** [comment]
Could you please send me in private your whole V1 export files ?
