### ISSUE TITLE
Import data from v0.3 to V2

### ISSUE THREAD

**Issue by gallak** [tbellembois/gochimitheque#48]
When import store location, its seems that there is a error on field mapping
we got parent entitie label inside color 

![image](https://user-images.githubusercontent.com/17747269/84257183-3c25e200-ab15-11ea-9c4a-68df8bf679b5.png)

**Comment by gallak** [comment]
as asked by mail

**Comment by Bismuth69** [comment]
There is still an import problem from V0.3 to V2.0.
Archived stock records have not been imported.
(V0.3: storage.archive = true).

**Comment by Bismuth69** [comment]
There is a bug in the import of storage locations, even if the option "can store" is checked, it is not possible to move a stock card in it.
To solve the problem, I unchecked "can store" then saved. Then I checked "can store" and saved.
That solved the problem, but I had to do it manually on my 60 storage locations.

**Comment by tbellembois** [comment]
> There is still an import problem from V0.3 to V2.0.
> Archived stock records have not been imported.
> (V0.3: storage.archive = true).

Yes this is expected.
[https://github.com/tbellembois/gochimitheque#read-me-first-](https://github.com/tbellembois/gochimitheque#read-me-first-)
