### ISSUE TITLE
Incompatibility export date format chimithèque to excel

### ISSUE THREAD

**Issue by Bismuth69** [tbellembois/gochimitheque#50]
When exporting stocks of "chimtheque" in CSV format, the date format is "14 May 20 14:18 +0200" which is not compatible with the Excel date format.

**Comment by tbellembois** [comment]
I have successfully imported into Excel 2016.
Do not open the file directly but import it as external data (text file), then choose "," as a separator..

**Comment by Bismuth69** [comment]
the problem is not the export but the format of dates.
Excel does not recognize the months in 3 letters.

01 **Jan** 01 00:00 UTC
