### ISSUE TITLE
bug ::: several managers per entity

### ISSUE THREAD

**Issue by Bismuth69** [tbellembois/gochimitheque#54]
I have entities with many users and I would have liked to have several managers per entity.

I have a server error when I want to validate

![image](https://user-images.githubusercontent.com/54662669/85688333-f26ef700-b6d1-11ea-8a37-5c34981d806b.png)

**Comment by tbellembois** [comment]
Thanks for reporting. I am on it.

**Comment by tbellembois** [comment]
You can get the compiled version from the trunk with the documentation [here](https://github.com/tbellembois/gochimitheque#get-the-latest-development-compiled-version).
