### ISSUE TITLE
bug reset password and display icon

### ISSUE THREAD

**Issue by Bismuth69** [tbellembois/gochimitheque#56]
We have a problem with resetting passwords. The captcha no longer appears when you click on reset.
Also, the icons no longer appear.
link between the two?

screenshot after clicking on reset password :
![image](https://user-images.githubusercontent.com/54662669/87159060-049b8880-c2c1-11ea-89c5-40be0f40fa14.png)

screenshot after authentication :
![image](https://user-images.githubusercontent.com/54662669/87158811-9ce53d80-c2c0-11ea-8dd0-6a405f30631d.png)

**Comment by tbellembois** [comment]
Have you reset your web browser cache ? I have updated the icons library and not cleaning the cache leads to this issue.

**Comment by Bismuth69** [comment]
Yes, the caches have been emptied. The main problem is that I didn't capture him and I have a lot of people with this problem. Strange thing, it works sometimes on some pc's that have the same configuration.

![chimitheque_labo_enr](https://user-images.githubusercontent.com/54662669/90219078-92f5b380-de05-11ea-83c9-1e7d1f745aa6.png)

![chimitheque_labo_dco](https://user-images.githubusercontent.com/54662669/90219126-aacd3780-de05-11ea-9488-3b2423a77e65.png)

**Comment by Bismuth69** [comment]
With Opera

![image](https://user-images.githubusercontent.com/54662669/90245448-fe09af00-de32-11ea-91d5-7837e7c05cf9.png)

**Comment by tbellembois** [comment]
Can you please post your Chimithèque startup command ?
