### ISSUE TITLE
bug on product data sheet: double hazard statement(s) H-EUH

### ISSUE THREAD

**Issue by Bismuth69** [tbellembois/gochimitheque#60]
when adding or updating a product sheet, if an H-sentence is duplicated, it causes "Internal Server Error".

This can happen when using the magic selector.

time="2020-09-18T08:48:03+02:00" level=error msg="create product error-UNIQUE constraint failed: producthazardstatements.producthazardstatements_product_id, producthazardstatements.producthazardstatements_hazardstatement_id" func="github.com/tbellembois/gochimitheque/handlers.(*Env).AppMiddleware.func1" file="/home/thbellem/workspace/workspace_go/src/github.com/tbellembois/gochimitheque/handlers/middleware.go:26"

![image](https://user-images.githubusercontent.com/54662669/93608205-a67ad800-f9ca-11ea-89d5-002e9b473c34.png)

**Comment by tbellembois** [comment]
I have never tested this case. Thanks for reporting.
