### ISSUE TITLE
product storage bug

### ISSUE THREAD

**Issue by Bismuth69** [tbellembois/gochimitheque#61]
When several different products are stored (e.g. sulfuric acid case: 7664-93-9) 
![image](https://user-images.githubusercontent.com/54662669/94013652-a99b0d00-fdaa-11ea-9e59-fa4873ac3316.png)

then switch to another product (ex CHLORFENVINPHOS CASE: 470-90-6), when you click on "store this product".
![image](https://user-images.githubusercontent.com/54662669/94014457-d7348600-fdab-11ea-8700-0bf3c0ac8ddd.png)

It is the previous product that is stored and not the selected one.
![image](https://user-images.githubusercontent.com/54662669/94014516-ef0c0a00-fdab-11ea-8d30-dcf9064ce351.png)

**Comment by tbellembois** [comment]
This button is removed in the next version. It was redundant with the one in the actions right to the products in the product list.

**Comment by tbellembois** [comment]
Fixed in wasm branch.
