### ISSUE TITLE
Installation avec docker

### ISSUE THREAD

**Issue by Rotoi** [tbellembois/gochimitheque#64]
Bonjour,

Je rencontre une erreur pour installer gochimitheque par la méthode du docker. En effet le processus est constamment dans l'état "Restarting".

Dans les logs du processus, ces erreurs apparaissent.

time="2021-01-19T10:37:23Z" level=info msg="- application version: devel"
time="2021-01-19T10:37:23Z" level=info msg="- application endpoint: http://127.0.0.1/"
time="2021-01-19T10:37:23Z" level=info msg="- application db: /data/storage.db"
time="2021-01-19T10:37:23Z" level=info msg="- opening database connection to /data/storage.db"
time="2021-01-19T10:37:23Z" level=fatal msg="unable to open database file: no such file or directory"

Il semblerait qu'une erreur se produise dans l'ouverture de la base de données. Où doit être ce fichier ?

La méthode "Quick start" fonctionne mais n'est pas recommandée en production.

Merci

Cordialement

**Comment by tbellembois** [comment]
Bonjour,

C'est un problème de permission sur le répertoire contenant la base sur le répertoire qui bind le répertoire `/data` du container.
Un `chmod o+rwx /data/docker-chimitheque/` (adapter le chemin) résoudra le problème.

Thomas

**Comment by Rotoi** [comment]
Merci pour votre retour.

J'ai la même erreur, voici les droits du dossier

drwxr-xrwx  3 root root 4096 Jan 18 11:40 docker-chimitheque

Celui-ci contient bien  un dossier chimitheque-db mais il est vide.

Cordialement

**Comment by tbellembois** [comment]
Quelles sont les permissions du dossier `chimitheque-db ` ?

**Comment by Rotoi** [comment]
Bonjour,

Je suis parvenu à l'installer en tant que service via la méthode "Classic way". Y a-t-il des conséquences à ne pas utiliser la méthode par docker ?

L'url d'accès est de la forme http://IP:8081/login, via les paramètres peut-on la réduire à http://IP ?

Merci 

Cordialement

**Comment by tbellembois** [comment]
Bonjour,

Non, aucune conséquence. Vous pouvez réduire votre URL en utilisant le paramètre `-listenport 80`.

**Comment by Rotoi** [comment]
Bonjour,

L'erreur suivante se produit :

 2021/02/04 10:34:15 [overseer] disabled. run failed: listen tcp :80: bind: permission denied

Les permissions de /usr/local/chimitheque/gochimitheque n'ont pas changé, ce sont celles-ci :
-rwxrw-rw- 1 chimitheque chimitheque 40235952 Dec  9  2019 gochimitheque

Cela permettra-t-il aussi de supprimer le /login en fin d'url ou il est obligatoire pour l'accès à la chimithèque ?

Cordialement

**Comment by Rotoi** [comment]
L'erreur venait du fait que le port 80 n'était pas ouvert dans le parefeu.

La commande est bien prise en compte, le site n'est plus accessible sur http://IP:8081/login mais ne fonctionne pas sur http://IP/login

Le fichier chimitheque.service contient ceci :

[Unit]
Description=Chimitheque
After=network.target

[Service]
ExecStart=/usr/local/chimitheque/gochimitheque -listenport 80
WorkingDirectory=/usr/local/chimitheque
User=chimitheque
Group=chimitheque

[Install]
WantedBy=multi-user.target

Le format est-il correct ?

Cordialement

**Comment by Rotoi** [comment]
Testé aussi avec 
ExecStart=/usr/local/chimitheque/gochimitheque -listenport=80

**Comment by tbellembois** [comment]
Pouvez vous donner les logs en lançant avec `/usr/local/chimitheque/gochimitheque -listenport 80 -debug` ?

**Comment by Rotoi** [comment]
Cela fonctionne en tapant directement la commande en tant que root. Il a fallu saisir la commande setcap 'cap_net_bind_service=+ep' /usr/local/chimitheque/gochimitheque  pour écouter sur le port 80 sans être root.

Le site est donc accessible via http://IP/login

Peut-on aussi s'affranchir du /login ?

Cordialement

**Comment by tbellembois** [comment]
Oui, dans la prochaine version il disparait.
