### ISSUE TITLE
date of creation and modification of product sheets

### ISSUE THREAD

**Issue by Bismuth69** [tbellembois/gochimitheque#65]
Add to the product file the date of creation and the date of the last modification.

Possibly, put this date in red if it is more than 2 years old (for example).

![image](https://user-images.githubusercontent.com/54662669/105727131-0c540f00-5f2b-11eb-9818-56d6cf7d9e01.png)

![image](https://user-images.githubusercontent.com/54662669/105727356-4ae9c980-5f2b-11eb-8252-564504898c2b.png)

**Comment by tbellembois** [comment]
Sorry but the product creation and modification date have been removed as the modification history.
