### ISSUE TITLE
Export Storage

### ISSUE THREAD

**Issue by Bismuth69** [tbellembois/gochimitheque#67]
Some information is missing in the stock export file :
- product_id (missing)
- product_casnumber (empty)
- product_specificity (empty)

there are also accent / carriage return problems when opening the file with excel. These problems disappear with "Libre Office".
Is it possible that it is compatible for both?

example Excel vs Libre Office
![image](https://user-images.githubusercontent.com/54662669/105733079-68219680-5f31-11eb-94e9-5a63b1e575d6.png)
![image](https://user-images.githubusercontent.com/54662669/105733232-9bfcbc00-5f31-11eb-9164-baa40010468b.png)

**Comment by tbellembois** [comment]
Look at https://github.com/tbellembois/gochimitheque/issues/57 for the missing export fields. It is fixed.
