### ISSUE TITLE
Mot de passe pour nouvel utilisateur

### ISSUE THREAD

**Issue by Rotoi** [tbellembois/gochimitheque#68]
Bonjour,

Lors de la création d'un utilisateur depuis l'interface de chimithèque, l'erreur "Internal Server Error" apparaît même si cela fonctionne.

La procédure de paramétrage de mot de passe de cet utilisateur passe-t-elle bien par l'envoi d'un mail de réinitialisation en cliquant sur "réinitialisation de mot de passe" depuis la page de connexion ?

Ce faisant, j'obtiens l'erreur "error sending the reinitialization mail" et ne reçoit pas le mail de réinitialisation.

Le serveur SMTP, le port et l'adresse émettrice sont bien renseignés en option de la commande ExecStart=/usr/local/chimitheque/gochimitheque  dans le fichier chimitheque.service, avec également l'option -mailserverusetls=true.

Mar 10 11:16:52 gochimitheque[546363]: time="2021-03-10T11:16:52+01:00" level=error msg="error sending the reinitialization mail-dial tcp: lookup _smtp.monSMTP.fr_ on [::1]:53: read udp [::1]:50578->[::1]:53: read: connection refused"
Mar 10 11:17:01 CRON[546535]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Mar 10 11:17:42 gochimitheque[546363]: time="2021-03-10T11:17:42+01:00" level=error msg="error sending the reinitialization mail-dial tcp: lookup _smtp.monSMTP.fr_ on [::1]:53: read udp [::1]:37335->[::1]:53: read: connection refused"
Mar 10 11:19:19 gochimitheque[546363]: time="2021-03-10T11:19:19+01:00" level=error msg="error sending the new person mail-dial tcp: lookup _smtp.monSMTP.fr_ on [::1]:53: read udp [::1]:43259->[::1]:53: read: connection refused"
Mar 10 12:07:49 gochimitheque[546363]: time="2021-03-10T12:07:49+01:00" level=error msg="error sending the reinitialization mail-dial tcp: lookup _smtp.monSMTP.fr_ on [::1]:53: read udp [::1]:37773->[::1]:53: read: connection refused"

Merci à vous.

Cordialement

**Comment by tbellembois** [comment]
Bonjour,

L'erreur qui apparait est lié au problème d'envoi de mail.
La réinitialisation de mot de passe envoie effectivement un mail à l'utilisateur pour lancer la procédure de réinitialisation.
Il s'agit sans doute d'un problème avec votre SMTP. 
Avez vous testé vos paramètres avec une autre application ?

Thomas

**Comment by Rotoi** [comment]
Bonjour,

Il y avait un souci avec le service de résolution de noms, le serveur smtp n'était ainsi pas résolu. C'est corrigé.

Je reçois bien un mail de réinitialisation m'invitant à cliquer sur un lien, celui-ci n'est pas cliquable et commence par /reset?token=

J'ai récupéré et ajouté cette partie à la suite de l'URL de chimithèque et j'ai reçu un deuxième mail avec le mot de passe temporaire. Peut-on plutôt recevoir le lien complet lors de l'envoi du premier mail ?

Est-ce bien la seule procédure pour configurer un mot de passe pour un nouvel utilisateur ?

Cordialement

**Comment by tbellembois** [comment]
Bonjour,

Je ne comprends pas votre question concernant le lien complet. Pouvez vous donner un exemple ?
Oui c'est la seule procédure.

**Comment by Rotoi** [comment]
Bonjour,

Comme je l'ai dit, voici le mail que je reçois.

`https://i.imgur.com/iJxEk0q.png`

Je dois récupérer cette partie du lien pour la coller après l'URL de chimithèque par laquelle j'accède à l'interface web sur le navigateur. Y a-t-il un souci et le lien n'est pas censé arriver sous cette forme mais complet et cliquable dans le mail ?

Cordialement

**Comment by tbellembois** [comment]
Effectivement il s'agit d'un bug. Pouvez vous me donner les paramètres de lancement de l'application (sans les mot de passe éventuels) ?

**Comment by Rotoi** [comment]
[Unit]
Description=Chimitheque
After=network.target

[Service]
ExecStart=/usr/local/chimitheque/gochimitheque -mailserveraddress=smtp.foo.fr -mailserverport=25 -mailserversender=chimitheque@foo.fr
WorkingDirectory=/usr/local/chimitheque
User=chimitheque
Group=chimitheque

[Install]
WantedBy=multi-user.target

C'est cela que vous souhaitiez ?

Cordialement

**Comment by tbellembois** [comment]
Oui.
Pouvez vous retester avec le binaire suivant:
https://drive.uca.fr/f/e67ab296bb9242daac10/?dl=1
?

**Comment by Rotoi** [comment]
J'ai cette page en le lançant :

`https://i.imgur.com/rHaESul.png`

**Comment by tbellembois** [comment]
Avez vous bien vidé votre cache ?

**Comment by Rotoi** [comment]
Oui, j'ai également testé avec d'autres navigateurs desquelles je n'avais pas accédé à chimitheque, idem.

**Comment by tbellembois** [comment]
Cette page apparait dès la page d'accueil ?

**Comment by Rotoi** [comment]
Oui effectivement, mais seulement avec le dernier binaire.

**Comment by tbellembois** [comment]
C'est étonnant, je vous le renvoit:
https://drive.uca.fr/f/e67ab296bb9242daac10/?dl=1

**Comment by Rotoi** [comment]
Bonjour,

Cela produit la même page avec ce binaire. Je l'ai téléchargé avec la commange wget -O gochimitheque https://drive.uca.fr/f/e67ab296bb9242daac10/?dl=1

**Comment by tbellembois** [comment]
Quel navigateur utilisez vous ?

**Comment by Rotoi** [comment]
Firefox. Testé également avec Chrome et Edge, idem.

Ce binaire fonctionne : https://github.com/tbellembois/gochimitheque/releases/latest/download/gochimitheque, mais avec le bug sur l'envoi du lien de réintialisation par mal.

**Comment by Rotoi** [comment]
Y a-t-il une autre manipulation à réaliser en dehors de remplacer l'ancien binaire par celui que vous m'avez envoyé et relancer le service chimitheque.service ?

**Comment by tbellembois** [comment]
Non.
Il faut vérifier que votre version de navigateur supporte bien le Web Assembly.
https://developer.mozilla.org/fr/docs/WebAssembly#compat-desktop

**Comment by Rotoi** [comment]
J'ai testé tous les navigateurs suscités dans leur dernière version. Ils sont compatibles.

Avez-vous ce même bug dans le l'url reçue par mail avec le binaire gochimitheque actuellement publié à cette adresse [https://github.com/tbellembois/gochimitheque/releases/latest/download/gochimitheque](url) ?

**Comment by Rotoi** [comment]
Cela fonctionne à présent, avec le binaire publié sur la page [en](https://github.com/tbellembois/gochimitheque) ajoutant l'option proxyurl=server. Le lien reçu est correct et cliquable et le mot de passe est bien réinitialisé.

Cependant, après avoir cliqué, l'url affichée dans le navigateur est :

http://localhost:8081//login?message=Un%20nouveau%20mot%20de%20passe%20temporaire%20a%20%c3%a9t%c3%a9%20envoy%c3%a9%20%c3%a0%20mail@foo.fr

Ce qui affichage une erreur de chargement de la page, au lieu de :

http://URL/login?message=Un%20nouveau%20mot%20de%20passe%20temporaire%20a%20%c3%a9t%c3%a9%20envoy%c3%a9%20%c3%a0%20mail@foo.fr

De même que lors d'une déconnexion, la page est redirigée vers http://localhost:8081/login et n'affiche rien.

Il semblerait qu'il faille ajouter l'url du serveur à la place de http://localhost:8081/ dans l'un des fichiers de configuration pour cela ?

**Comment by tbellembois** [comment]
Pourriez vous afficher la console développeur et voir si elle vous remonte des erreurs ?

**Comment by Rotoi** [comment]
La seule erreur est : [Exception... "Favicon at "https://appserver.foo.fr/favicon.ico" failed to load: Not Found."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: onStopRequest :: line 253"  data: no]

À quoi sert le paramètre -proxypath ?

**Comment by tbellembois** [comment]
Si votre serveur est hébergé à:
https://monserveur.foo.fr/chimitheque alors
- proxyurl = https://monserveur.foo.fr
- proxypath = /chimitheque

**Comment by Rotoi** [comment]
C'est réglé.

Par contre, lors de la création d'un compte, le mail suivant est reçu.

> 
>        Un compte Chimithèque a été créé pour vous.
> 
>         Vous pouvez maintenant initialiser votre mot de passe.
> 
>         Rendez vous sur la page de connexion http://localhost:8081/login, entrez votre adresse mail assane.ndoye@univ-amu.fr et cliquez sur le lien "réinitialiser mon mot de passe ".
> 
>         Vous recevrez ensuite un mot de passe temporaire.

Quel paramètre doit être modifié afin que http://localhost:8081/login soit remplacé par l'url du serveur ?

**Comment by Rotoi** [comment]
Y a-t-il la possibilité de modifier http://localhost:8081/login par l'url du serveur dans le mail de bienvenue, et pour sauvegarder la base de données, faut-il sauvegarder /user/local/chimitheque/storage.db, storage.db-shm, storage.db-wal ou seulement storage.db ?

Merci.

**Comment by tbellembois** [comment]
Ce sont les deux paramètres cités ci dessus qui génèrent l'URL.

Vous pouvez sauvegarder uniquement storage.db mais le mieux est encore d'utiliser la méthode cité ici:
https://github.com/tbellembois/gochimitheque/tree/wasm#database-backup

**Comment by Rotoi** [comment]
Ok pour la sauvegarde.

Pour l'URL, comme dit proxyurl est renseigné et je n'ai pas besoin de proxypath. L'URL de réinitialisation de mot de passe est pourtant correctement générée et fonctionne, pas celle du mail de bienvenue.

**Comment by tbellembois** [comment]
Voici la dernière version de développement https://drive.uca.fr/f/e67ab296bb9242daac10/?dl=1

Merci de ré essayer avec cette version.

**Comment by Rotoi** [comment]
Avec ce binaire j'ai toujours cette page : [https://i.imgur.com/10Tx1vq.png](url)

Voici ma configuration : 
Distributon ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal

**Comment by tbellembois** [comment]
Avec quelle URL ?

**Comment by Rotoi** [comment]
Via la même que celle utilisée avec l'ancien binaire où cela fonctionne, avec l'adresse IP du serveur ou le nom enregistré dans le DNS. L'accès se fait en https.
https://IP
https://nomDNS

L'URL est réécrite pour s'affranchir du /login. J'ai testé en retirant la directive dans le fichier de configuration nginx, idem.

**Comment by tbellembois** [comment]
Il ne faut pas masquer /login.
L'accès est maintenant fait directement à la racine du site.

**Comment by Rotoi** [comment]
Je viens de retester avec cette version sans la réécriture de l'URL, l'étape "Chargement du Module Assembly" prend entre 33 et 36 secondes mais cela fonctionne, l'URL est correctement générée dans le mail de bienvenue, et le bug empêchant de modifier un utilisateur créé sans entité est corrigé.

Merci à vous

**Comment by tbellembois** [comment]
Oui c'est prévu. Le module Web Assembly n'est chargé qu'une fois au premier accès. Pour le moment il n'est pas compressé d'où le temps de chargement.

**Comment by Rotoi** [comment]
Bien.

Concernant la restauration d'une base de données, il suffit de renommer storage.sq3 en storage.db et de le placer dans le dossier source de chimithèque ?

**Comment by tbellembois** [comment]
oui
