### ISSUE TITLE
Problème upgrade

### ISSUE THREAD

**Issue by chambon** [tbellembois/gochimitheque#72]
docker-compose down
    docker-compose pull
    docker-compose up -d --force-recreate

A la suite de ces commandes 
l'appli dysfonctionne et ne permet plus d'ajouter, visualiser les produits, problème bloquant
time="2021-05-11T20:33:49Z" level=error msg="error getting the products-no such column: p.product_number_per_carton"

Merci

**Comment by tbellembois** [comment]
L'upgrade est il bien depuis la dernière stable 2.0.6 ?

**Comment by chambon** [comment]
depuis

version e77987ed1201bc1cdd7b9a691d619d915b5ea3eb


Le 12/05/2021 à 09:16, Thomas Bellembois a écrit :

**Comment by tbellembois** [comment]
Voilà le problème. Les upgrades ne  fonctionnent que de stable à stable.

**Comment by chambon** [comment]
ok je ne savais pas et comment revenir désormais sur une appli "docker" 
stable ?

Le 12/05/2021 à 09:21, Thomas Bellembois a écrit :

**Comment by tbellembois** [comment]
Votre base est déjà en production ?

**Comment by chambon** [comment]
A la question :

ai je utilisé la partie production installation : la réponse est oui

L'outil est en production pour notre unité : la réponse est non

Le 12/05/2021 à 09:45, Thomas Bellembois a écrit :

**Comment by tbellembois** [comment]
Si l'outil n'est pas en production le plus simple est de supprimer la base.

**Comment by chambon** [comment]
la base sqlite n'est ce pas et non le conteneur

ok

et on repart sur master ou wasm avec du docker

Le 12/05/2021 à 12:09, Thomas Bellembois a écrit :

**Comment by tbellembois** [comment]
Oui les fichiers storage.db*.

J'ai fusionné la branche wasm à master lors de l'annonce de la nouvelle version, donc repartez sur master avec Docker.

**Comment by chambon** [comment]
ok merci

Le 12/05/2021 à 12:18, Thomas Bellembois a écrit :

**Comment by chambon** [comment]
pour la doc

Attention le tag est noté : v2.... or il faut noter 2.07

Le 12/05/2021 à 12:18, Thomas Bellembois a écrit :

**Comment by chambon** [comment]
Suppression de base faite

Réinstallation ok

et en 2.0.7






Le 12/05/2021 à 12:09, Thomas Bellembois a écrit :

**Comment by chambon** [comment]
C:\Users\chambon\Downloads\2021-05-12 14_25_07-chimietheque.png

**Comment by chambon** [comment]
il faut redémarrer les conteneurs
