### ISSUE TITLE
Mail enregistrement nouvel utilisateur

### ISSUE THREAD

**Issue by chambon** [tbellembois/gochimitheque#73]
Bonjour,
je souhaiterais personnaliser l'envoi de mail lors de l'inscription d'un nouvel utilisateur:
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
     Un compte Chimithèque a été créé pour vous.
        Vous pouvez maintenant initialiser votre mot de passe.
        Rendez vous sur la page de connexion http://localhost:8081, entrez votre adresse mail xxxxxxx et cliquez sur le lien "réinitialiser mon mot de passe ".

        Vous recevrez ensuite un mot de passe temporaire.
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
De plus l'url de connexion n'est pas la bonne, comment modifier ?

Merci

**Comment by chambon** [comment]
...pas de nouvelles

**Comment by tbellembois** [comment]
Bonjour, pour que l'adresse renseignée dans le mail soit correcte il faut utiliser le paramètre `-proxypath` et `-proxyurl` au lancement de l'application.

Le message ne peut pas etre changé sans recompiler. Ils sont codés dans les fichiers du répertoire `locales`.

**Comment by chambon** [comment]
Parfait merci
