### ISSUE TITLE
CAS :  remplissage automatique après sélection CAS (ou ajout)

### ISSUE THREAD

**Issue by chambon** [tbellembois/gochimitheque#74]
Si le CAS est bien unique, serait il possible de remplir les champs automatiquement avec toutes les infos nécessaires ?
Merci

**Comment by tbellembois** [comment]
duplicate #22

**Comment by chambon** [comment]
je ne parle pas de l'authentification CAS mais des pduits chimiques

**Comment by tbellembois** [comment]
Je vois deux freins:
- deux produits peuvent avoir le meme CAS (avec une spécificité différente)
- il faut une source d'information fiable pour pouvoir extraire les données

**Comment by chambon** [comment]
ok parfait, j'avais cru comprendre que le CAS était unique, désolé

Le 23/06/2021 à 12:00, Thomas Bellembois a écrit :
