### ISSUE TITLE
Erreur import from https://chimitheque.ens-lyon.fr :  Docker

### ISSUE THREAD

**Issue by chambon** [tbellembois/gochimitheque#76]
docker: version 2.0.7
1. docker stop chimitheque
2. modification fichier yml
lorsqu'on décommente:
        #    - CHIMITHEQUE_IMPORTFROM=https://chimitheque.ens-lyon.fr
3.docker-compose up -d chimitheque

erreur suivante:
502 pour nginx sur le navigateur web
si on laisse https://chimitheque.ens-lyon.fr , on a une erreur de certificat
si on passe en http on :
time="2021-05-25T17:16:52Z" level=error msg="can not get remote products Get \"http://chimitheque.ens-lyon.fr/e/products\": dial tcp 140.77.51.16:80: connect: connection refused"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x8e7cfb]

**Comment by tbellembois** [comment]
Corrigé dans la dernière image tagguée "latest".

**Comment by chambon** [comment]
![image](https://user-images.githubusercontent.com/11677365/123060318-e879f400-d40a-11eb-93cc-19b88f7d7a5e.png)

**Comment by chambon** [comment]
pas de issue = 76 ?

**Comment by tbellembois** [comment]
dernière image tagguée "latest" = dernière image de la branche devel pas encore tagguée
