### ISSUE TITLE
Formules brutes avec parenthèses

### ISSUE THREAD

**Issue by Rotoi** [tbellembois/gochimitheque#77]
Bonjour,

Il n'est pas possible de créer un produit dont la formule brute contient des parenthèses. Comme Al2(SO4)3 

https://i.imgur.com/0Yf8qlg.png

> time="2021-06-04T10:00:31+02:00" level=error msg="error calling f-wrong lowercase atoms in formula"

Pouvez-vous intégrer le support de cette écriture ?

La version utilisée est la dernière disponible en téléchargement à l'adresse https://drive.uca.fr/f/e67ab296bb9242daac10/?dl=1

Certains utilisateurs me reportent toujours des bugs de connexion avec Firefox sur cette version, à savoir que rien ne se passe en cliquant sur "entrer" après avoir saisi les identifiants et mot de passe.

**Comment by tbellembois** [comment]
C'est un bug. Les parenthèses sont normalement possibles. Je regarde.

**Comment by tbellembois** [comment]
Vu avec Delphine Pitrat. Dans une formule brute il n'y a pas de parenthèses. Il s'agit d'une formule semi développé. Ce n'est donc pas un bug.
