### ISSUE TITLE
Error import data into database

### ISSUE THREAD

**Issue by frampoldi** [tbellembois/gochimitheque#81]
Bonjour
je viens de installer et tester le logiciel chimitheque mais quand je veux récupérer les donnes depuis les site avec la commande:

./gochimitheque --debug --importfrom=https://chimitheque.ens-lyon.fr

J'ai l'erreur suivant:

DEBU[0003] GetProductsCasNumberByLabel                   cas="{0 {6995 true} {130-00-7 true} { false}}" label=130-00-7
DEBU[0003] GetProductsCasNumberByLabel                   label=627-49-6
DEBU[0003] GetProductsCasNumberByLabel                   cas="{0 {6996 true} {627-49-6 true} { false}}" label=627-49-6
DEBU[0003] GetProductsCasNumberByLabel                   label=20491-53-6
DEBU[0003] GetProductsCasNumberByLabel                   cas="{0 {6997 true} {20491-53-6 true} { false}}" label=20491-53-6
DEBU[0003] GetProductsCasNumberByLabel                   label="\t4006-38-6"
DEBU[0003] GetProductsCasNumberByLabel                   cas="{0 {6998 true} {\t4006-38-6 true} { false}}" label="\t4006-38-6"
DEBU[0003] GetProductsNameByLabel                        label="DRAQ 5"
DEBU[0003] new name DRAQ 5
**ERRO[0003] product error - FOREIGN KEY constraint failed
ERRO[0003] sql:INSERT INTO product (category,unit_temperature,name,person,product_temperature,product_restricted,producerref,product_msds,product_radioactive) VALUES (?,?,?,?,?,?,?,?,?)
ERRO[0003] can not create product FOREIGN KEY constraint failed**

Cordialement

Fabio

**Comment by tbellembois** [comment]
Bonjour,

L'erreur est due au fait que la base de l'ENS de Lyon n'est pas la même que celle de la dernière version stable que vous utilisez.
En effet l'ENS utilise une instance toujours plus avancée qui deviendra la future version stable.
De gros changements ont été effectués dans la structure de la base depuis la dernière version stable.

La solution la plus simple serait que l'autres établissements acceptent d'exposer leur liste de produits en activant le paramètre `enablepublicproductsendpoint`. Je vais lancer un appel sur la liste dans ce sens.

**Comment by SiRiLiS** [comment]
Bonjour,
est-ce que il y a des nouvelles sur ce point? Où on peut trouver la liste des autres etablissements qui ont activé le parametre enablepublicproductsendpoint?

Merci

Fabio

**Comment by tbellembois** [comment]
Bonjour,

Je clôs cette issue. Aucun établissement ne s'est fait connaitre pour partager sa base. Le mieux est de renouveller la demande via la liste de diffusion.
