### ISSUE TITLE
scanner qrcode

### ISSUE THREAD

**Issue by Bismuth69** [tbellembois/gochimitheque#92]
Je viens de créer un nouveau stock sur un serveur test v2.0.8, et je viens de me rendre compte que le QRCode a changé pour ne générer que le numéro de la fiche stock, ex :  #4789. 

![image](https://github.com/tbellembois/gochimitheque/assets/54662669/546a481c-c761-446c-957a-7f848baec2ea)

du coup, en le scannant ça marche, mais j'ai l'impression que les anciens QRCode du type : https://chimitheque.institut.fr/v/storages?storage=4789 ne marche plus. Erreur de ma part ou est-ce que ça veut dire qu'il faut réimprimer tous les QRCode ? :-/

**Comment by tbellembois** [comment]
Bonjour,

oui effectivement le qrcode n'encode plus que l'ID. Quel usage en faite vous ?

**Comment by Bismuth69** [comment]
je m'en servais pour personnaliser les étiquette en faisant un export de la base stock et faire ainsi du publipostage.
Ce n'est pas grave en soit, mais j'ai l'impression que toutes mes anciennes étiquettes ne marche plus.

**Comment by tbellembois** [comment]
Je clos cette ancienne issue. La génération du qrcode ne changera plus dans les futures versions.
