### ISSUE TITLE
bug stocks par recherche avancée via entité

### ISSUE THREAD

**Issue by Bismuth69** [tbellembois/gochimitheque#93]
V2.0.8, lorsque l'on fait une recherche avancé par entité dans les stocks par entité, la recherche nous renvoie la totalité des stocks et pas juste les stocks de l'entité.  (pas de pb pour les fiches produits)

Stocks sans recherche avancé
![image](https://github.com/tbellembois/gochimitheque/assets/54662669/ab1a77a7-4ac2-48f8-9d5e-8dfcc4d43254)

Stocks avec recherche avancé pour une entité
![image](https://github.com/tbellembois/gochimitheque/assets/54662669/15b44f95-3d5a-4e71-8817-4770df2c26e8)

**Comment by tbellembois** [comment]
Fixed in master branch.
