### ISSUE TITLE
erreur filtre ldap

### ISSUE THREAD

**Issue by GuillaumeFabre69** [tbellembois/gochimitheque#96]
Bonjour,
j'utilise la version 2.0.8 en docker et j'ai une erreur de filtre ldap lorsque je veux m'authentifier avec un active directory
```
chimitheque  | 2023-09-20T07:34:20.597054733Z time="2023-09-20T07:34:20Z" level=error msg="LDAP Result Code 201 \"Filter Compile Error\": ldap: filter does not start with an '('"
chimitheque  | 2023-09-20T07:34:20.597144639Z time="2023-09-20T07:34:20Z" level=error msg="LDAP user bind error-LDAP Result Code 201 \"Filter Compile Error\": ldap: filter does not start with an '('"
chimitheque  | 2023-09-20T07:34:20.598886607Z time="2023-09-20T07:34:20Z" level=error msg="LDAP Result Code 201 \"Filter Compile Error\": ldap: filter does not start with an '(' LDAP user bind error"
```

Voici la configuration du fichier docker-compose.yml
```
- CHIMITHEQUE_LDAPSERVERURL=ldap://xxxxxx/dc=xxx,dc=xxx,dc=fr
- CHIMITHEQUE_LDAPSERVERUSERNAME=CN=xxx,OU=xxx,DC=xxx,DC=xxx,DC=fr
- CHIMITHEQUE_LDAPSERVERPASSWORD=********
- CHIMITHEQUE_LDAPUSERSEARCHBASEDN=DC=xxx,DC=xxx,DC=fr
- CHIMITHEQUE_LDAPGROUPSEARCHBASEDN=DC=xxx,DC=xxx,DC=fr
# memberOf attribute must be provided by the LDAP server
- CHIMITHEQUE_LDAPUSERSEARCHFILTER=(&(mail=%s)(objectclass=user))
# cn attribute must be provided by the LDAP server
- CHIMITHEQUE_LDAPGROUPSEARCHFILTER=(cn=%s)
```

Voyez-vous une erreur possible dans la configuration du fichier docker-compose ?

Merci

**Comment by tbellembois** [comment]
Bonjour,

essayez en entourant les filtre avec des parenthèses:
(DC=xxx,DC=xxx,DC=fr)

**Comment by tbellembois** [comment]
Avez vous un proxy http en frontal de Chimithèque ?

**Comment by GuillaumeFabre69** [comment]
J'ai pu corriger l'erreur 502 en enlevant dc=xxx,dc=xxx,dc=fr de ldap://xxxxxx/dc=xxx,dc=xxx,dc=fr

En revanche j'ai toujours l'erreur
```
chimitheque  | 2023-09-25T08:16:04.152516541Z time="2023-09-25T08:16:04Z" level=error msg="LDAP Result Code 201 \"Filter Compile Error\": ldap: filter does not start with an '('"
chimitheque  | 2023-09-25T08:16:04.152639510Z time="2023-09-25T08:16:04Z" level=error msg="LDAP user bind error-LDAP Result Code 201 \"Filter Compile Error\": ldap: filter does not start with an '('"
chimitheque  | 2023-09-25T08:16:04.153009588Z time="2023-09-25T08:16:04Z" level=error msg="LDAP Result Code 201 \"Filter Compile Error\": ldap: filter does not start with an '(' LDAP user bind error"
chimitheque  | 2023-09-25T08:16:04.153345621Z 2023/09/25 08:16:04 http: superfluous response.WriteHeader call from github.com/tbellembois/gochimitheque/handlers.(*Env).AppMiddleware.func1 (middleware.go:40)
```

aussi bien avec le compte admin@chimitheque.fr et mot de passe par défaut qu'avec les comptes LDAP (Active Directory dans mon cas)

La config actuelle du docker-compose pour le LDAP est celle-ci :
```
# LDAP server parameters
            - CHIMITHEQUE_LDAPSERVERURL=ldap://xxx.xxx.xxx.fr
            - CHIMITHEQUE_LDAPSERVERUSERNAME=CN=xxx xxx,OU=xxx xxx,DC=xxx,DC=xxx,DC=fr
            - CHIMITHEQUE_LDAPSERVERPASSWORD=***********
            - CHIMITHEQUE_LDAPUSERSEARCHBASEDN=(DC=xxx,DC=xxx,DC=fr)
            - CHIMITHEQUE_LDAPGROUPSEARCHBASEDN=(DC=xxx,DC=xxx,DC=fr)
            # memberOf attribute must be provided by the LDAP server
            - CHIMITHEQUE_LDAPUSERSEARCHFILTER=(&(mail=%s)(objectClass=user))
            # cn attribute must be provided by the LDAP server
            - CHIMITHEQUE_LDAPGROUPSEARCHFILTER=(cn=%s)
            # auto create users in db with LDAP authentication
            - CHIMITHEQUE_AUTOCREATEUSER=true
  ```

Merci de votre aide

**Comment by tbellembois** [comment]
Il manque aussi les parenthèses pour la ligne:
            - CHIMITHEQUE_LDAPSERVERUSERNAME=CN=xxx xxx,OU=xxx xxx,DC=xxx,DC=xxx,DC=fr

**Comment by tbellembois** [comment]
Pouvez vous tester en changeant le binding the /data dans le docker-compose.yml:

```
volumes:
            - /tmp:/data
```

**Comment by GuillaumeFabre69** [comment]
Hélas, toujours la même erreur

`time="2023-10-31T13:42:14Z" level=error msg="LDAP user bind error-LDAP Result Code 201 \"Filter Compile Error\": ldap: filter does not start with an '('" func="main.buildEndpoints.(*Env).AppMiddleware.func4" file="/go/src/github.com/tbellembois/gochimitheque/handlers/middleware.go:32"
time="2023-10-19T13:53:48Z" level=error msg="LDAP user bind error-LDAP Result Code 201 \"Filter Compile Error\": ldap: filter does not start with an '('" func="main.buildEndpoints.(*Env).AppMiddleware.func4" file="/go/src/github.com/tbellembois/gochimitheque/handlers/middleware.go:32"
time="2023-10-19T13:53:56Z" level=error msg="LDAP user bind error-LDAP Result Code 201 \"Filter Compile Error\": ldap: filter does not start with an '('" func="main.buildEndpoints.(*Env).AppMiddleware.func4" file="/go/src/github.com/tbellembois/gochimitheque/handlers/middleware.go:32"
time="2023-10-19T14:00:11Z" level=error msg="LDAP user bind error-LDAP Result Code 201 \"Filter Compile Error\": ldap: filter does not start with an '('" func="main.buildEndpoints.(*Env).AppMiddleware.func4" file="/go/src/github.com/tbellembois/gochimitheque/handlers/middleware.go:32"
time="2023-10-19T14:14:10Z" level=error msg="LDAP user bind error-LDAP Result Code 201 \"Filter Compile Error\": ldap: filter does not start with an '('" func="main.buildEndpoints.(*Env).AppMiddleware.func4" file="/go/src/github.com/tbellembois/gochimitheque/handlers/middleware.go:32"
`
Avec cette configuration
`# LDAP server parameters
            - CHIMITHEQUE_LDAPSERVERURL=ldap://xxx.xxx.xxx.fr/
            - CHIMITHEQUE_LDAPSERVERUSERNAME=(CN=xxx xxx,OU=xxx,DC=xxx,DC=xxx,DC=fr)
            - CHIMITHEQUE_LDAPSERVERPASSWORD=*************
            - CHIMITHEQUE_LDAPUSERSEARCHBASEDN=(DC=xxx,DC=xxx,DC=fr)
            - CHIMITHEQUE_LDAPGROUPSEARCHBASEDN=(DC=xxx,DC=xxx,DC=fr)
            # memberOf attribute must be provided by the LDAP server
            - CHIMITHEQUE_LDAPUSERSEARCHFILTER=(&(mail=%s)(objectclass=user))
            # cn attribute must be provided by the LDAP server
            - CHIMITHEQUE_LDAPGROUPSEARCHFILTER=(cn=%s)
            # auto create users in db with LDAP authentication
            - CHIMITHEQUE_AUTOCREATEUSER=true
`

**Comment by tbellembois** [comment]
Pouvez vous me fournir le log complet depuis le démarrage ?

**Comment by GuillaumeFabre69** [comment]
Voici le log complet, avec démarrage des conteneurs, puis accès au site web et tentative d'authentification AD

`chimitheque  | 2023-11-02T09:28:14.698565090Z parameters:
chimitheque  | 2023-11-02T09:28:14.698704514Z -ldapserverurl ldap://XXX.XXX.XXX.fr/
chimitheque  | 2023-11-02T09:28:14.698751997Z -ldapserverusername (CN=XXX,OU=XXX,DC=XXX,DC=XXX,DC=fr)
chimitheque  | 2023-11-02T09:28:14.698856763Z -ldapserverpassword ************
chimitheque  | 2023-11-02T09:28:14.699405915Z -ldapgroupsearchbasedn (DC=XXX,DC=XXX,DC=fr)
chimitheque  | 2023-11-02T09:28:14.699450157Z -ldapusersearchbasedn (DC=XXX,DC=XXX,DC=fr)
chimitheque  | 2023-11-02T09:28:14.699459959Z -ldapusersearchfilter (&(mail=%s)(objectclass=user))
chimitheque  | 2023-11-02T09:28:14.699469149Z -ldapgroupsearchfilter (cn=%s)
chimitheque  | 2023-11-02T09:28:14.699477631Z -autocreateuser
chimitheque  | 2023-11-02T09:28:14.699486111Z -dockerport 8081
chimitheque  | 2023-11-02T09:28:14.699494532Z -appurl https://chimitheque.XXX.XXX.fr
chimitheque  | 2023-11-02T09:28:14.699503073Z -apppath /chimitheque/
chimitheque  | 2023-11-02T09:28:14.699511543Z -mailserveraddress smtp.XXX.XXX.fr
chimitheque  | 2023-11-02T09:28:14.699520141Z -mailserverport 465
chimitheque  | 2023-11-02T09:28:14.699528604Z -mailserversender XXX.XXX@XXX.XXX.fr
chimitheque  | 2023-11-02T09:28:14.699596623Z -mailserverusetls
chimitheque  | 2023-11-02T09:28:14.699610474Z -enablepublicproductsendpoint
chimitheque  | 2023-11-02T09:28:14.699741228Z -admins XXX.XXX@XXX.XXX.fr
chimitheque  | 2023-11-02T09:28:14.699919150Z -debug
chimitheque  | 2023-11-02T09:28:14.699934628Z -logfile /var/log/chimitheque.log
chimitheque  | 2023-11-02T09:28:14.700186639Z command:
chimitheque  | 2023-11-02T09:28:14.700359079Z /var/www-data/gochimitheque -dbpath /data -appurl https://chimitheque.XXX.XXX.fr -apppath /chimitheque/ -dockerport 8081 -ldapserverurl ldap://XXX.XXX.XXX.fr/ -ldapserverusername (CN=XXX,OU=XXX,DC=XXX,DC=XXX,DC=fr) -ldapserverpassword ************ -ldapgroupsearchbasedn (DC=XXX,DC=XXX,DC=fr) -ldapgroupsearchfilter (cn=%s) -ldapusersearchbasedn (DC=XXX,DC=XXX,DC=fr) -ldapusersearchfilter (&(mail=%s)(objectclass=user)) -autocreateuser -mailserveraddress smtp.XXX.XXX.fr -mailserverport 465 -mailserversender XXX.XXX@XXX.XXX.fr -mailserverusetls -enablepublicproductsendpoint -admins XXX.XXX@XXX.XXX.fr -logfile /var/log/chimitheque.log -debug
chimitheque  | 2023-11-02T09:28:14.766401527Z time="2023-11-02T09:28:14Z" level=info msg="- application version: 20231019"
chimitheque  | 2023-11-02T09:28:14.766467794Z time="2023-11-02T09:28:14Z" level=info msg="- application endpoint: https://chimitheque.XXX.XXX.fr/chimitheque/"
chimitheque  | 2023-11-02T09:28:14.766603985Z time="2023-11-02T09:28:14Z" level=info msg="- opening database connection to /data/storage.db"
chimitheque  | 2023-11-02T09:28:15.198191683Z time="2023-11-02T09:28:15Z" level=info msg="- creating database if needed"
chimitheque  | 2023-11-02T09:28:15.198223512Z time="2023-11-02T09:28:15Z" level=info msg="  creating sqlite tables"
chimitheque  | 2023-11-02T09:28:15.201366392Z time="2023-11-02T09:28:15Z" level=info msg="  user_version:8"
chimitheque  | 2023-11-02T09:28:15.202361893Z time="2023-11-02T09:28:15Z" level=info msg="  vacuuming database"
chimitheque  | 2023-11-02T09:28:15.311204372Z time="2023-11-02T09:28:15Z" level=info msg="- running maintenance job"
nginx        | 2023-11-02T09:28:13.447208294Z /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
chimitheque  | 2023-11-02T09:28:15.335406719Z time="2023-11-02T09:28:15Z" level=info msg="- application listening on :8081"
nginx        | 2023-11-02T09:28:13.447258555Z /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx        | 2023-11-02T09:28:13.495709909Z /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx        | 2023-11-02T09:28:13.705398601Z 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx        | 2023-11-02T09:28:13.902961393Z 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx        | 2023-11-02T09:28:13.903327981Z /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx        | 2023-11-02T09:28:14.041124443Z 20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/nginx-chimitheque.conf.template to /etc/nginx/conf.d/nginx-chimitheque.conf
nginx        | 2023-11-02T09:28:14.091245559Z /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx        | 2023-11-02T09:28:14.106819187Z /docker-entrypoint.sh: Configuration complete; ready for start up
nginx        | 2023-11-02T09:28:35.224959680Z 1XX.2XX.1XX.2XX - - [02/Nov/2023:09:28:35 +0000] "GET /chimitheque/ HTTP/1.1" 200 20341 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0" "-"
nginx        | 2023-11-02T09:28:35.449021087Z 1XX.2XX.1XX.2XX - - [02/Nov/2023:09:28:35 +0000] "GET /chimitheque/static/css/bootstrap-colorpicker.min.css HTTP/1.1" 200 1882 "https://chimitheque.XXX.XXX.fr/chimitheque/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0" "-"
nginx        | 2023-11-02T09:28:35.449787660Z 1XX.2XX.1XX.2XX - - [02/Nov/2023:09:28:35 +0000] "GET /chimitheque/static/css/bootstrap-table.min.css HTTP/1.1" 200 2372 "https://chimitheque.XXX.XXX.fr/chimitheque/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0" "-"
nginx        | 2023-11-02T09:28:35.450095553Z 1XX.2XX.1XX.2XX - - [02/Nov/2023:09:28:35 +0000] "GET /chimitheque/static/css/bootstrap-toggle.min.css HTTP/1.1" 200 555 "https://chimitheque.XXX.XXX.fr/chimitheque/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0" "-"
nginx        | 2023-11-02T09:28:35.461903252Z 1XX.2XX.1XX.2XX - - [02/Nov/2023:09:28:35 +0000] "GET /chimitheque/static/css/chimitheque.css HTTP/1.1" 200 936 "https://chimitheque.XXX.XXX.fr/chimitheque/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0" "-"
nginx        | 2023-11-02T09:28:35.465085299Z 1XX.2XX.1XX.2XX - - [02/Nov/2023:09:28:35 +0000] "GET /chimitheque/static/css/fontawesome.all.min.css HTTP/1.1" 200 12686 "https://chimitheque.XXX.XXX.fr/chimitheque/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0" "-"
nginx        | 2023-11-02T09:28:35.470806614Z 1XX.2XX.1XX.2XX - - [02/Nov/2023:09:28:35 +0000] "GET /chimitheque/static/css/materialdesignicons.min.css HTTP/1.1" 200 48567 "https://chimitheque.XXX.XXX.fr/chimitheque/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0" "-"
nginx        | 2023-11-02T09:28:35.484822651Z 1XX.2XX.1XX.2XX - - [02/Nov/2023:09:28:35 +0000] "GET /chimitheque/static/js/bootstrap-table.min.js HTTP/1.1" 200 35332 "https://chimitheque.XXX.XXX.fr/chimitheque/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0" "-"
nginx        | 2023-11-02T09:28:35.490088112Z 1XX.2XX.1XX.2XX - - [02/Nov/2023:09:28:35 +0000] "GET /chimitheque/static/js/bootstrap-colorpicker.min.js HTTP/1.1" 200 20784 "https://chimitheque.XXX.XXX.fr/chimitheque/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0" "-"
nginx        | 2023-11-02T09:28:35.492220881Z 1XX.2XX.1XX.2XX - - [02/Nov/2023:09:28:35 +0000] "GET /chimitheque/static/css/bootstrap.min.css HTTP/1.1" 200 23854 "https://chimitheque.XXX.XXX.fr/chimitheque/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0" "-"
nginx        | 2023-11-02T09:28:35.495142677Z 1XX.2XX.1XX.2XX - - [02/Nov/2023:09:28:35 +0000] "GET /chimitheque/static/js/jquery.validate.min.js HTTP/1.1" 200 7862 "https://chimitheque.XXX.XXX.fr/chimitheque/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0" "-"
nginx        | 2023-11-02T09:28:35.496530365Z 1XX.2XX.1XX.2XX - - [02/Nov/2023:09:28:35 +0000] "GET /chimitheque/static/js/jquery.validate.additional-methods.min.js HTTP/1.1" 200 6412 "https://chimitheque.XXX.XXX.fr/chimitheque/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0" "-"
nginx        | 2023-11-02T09:28:35.497639183Z 1XX.2XX.1XX.2XX - - [02/Nov/2023:09:28:35 +0000] "GET /chimitheque/static/css/select2.min.css HTTP/1.1" 200 2008 "https://chimitheque.XXX.XXX.fr/chimitheque/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0" "-"
nginx        | 2023-11-02T09:28:35.498662571Z 1XX.2XX.1XX.2XX - - [02/Nov/2023:09:28:35 +0000] "GET /chimitheque/static/css/trumbowyg.min.css HTTP/1.1" 200 3086 "https://chimitheque.XXX.XXX.fr/chimitheque/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0" "-"
nginx        | 2023-11-02T09:28:35.505068324Z 1XX.2XX.1XX.2XX - - [02/Nov/2023:09:28:35 +0000] "GET /chimitheque/static/js/select2.full.min.js HTTP/1.1" 200 22047 "https://chimitheque.XXX.XXX.fr/chimitheque/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0" "-"
nginx        | 2023-11-02T09:28:35.505725788Z 1XX.2XX.1XX.2XX - - [02/Nov/2023:09:28:35 +0000] "GET /chimitheque/static/css/print.css HTTP/1.1" 200 681 "https://chimitheque.XXX.XXX.fr/chimitheque/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0" "-"
nginx        | 2023-11-02T09:28:35.506572749Z 1XX.2XX.1XX.2XX - - [02/Nov/2023:09:28:35 +0000] "GET /chimitheque/static/css/trumbowyg.colors.min.css HTTP/1.1" 200 519 "https://chimitheque.XXX.XXX.fr/chimitheque/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0" "-"
nginx        | 2023-11-02T09:28:35.512882552Z 1XX.2XX.1XX.2XX - - [02/Nov/2023:09:28:35 +0000] "GET /chimitheque/static/js/jquery.min.js HTTP/1.1" 200 30971 "https://chimitheque.XXX.XXX.fr/chimitheque/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0" "-"
nginx        | 2023-11-02T09:28:35.514395659Z 1XX.2XX.1XX.2XX - - [02/Nov/2023:09:28:35 +0000] "GET /chimitheque/static/js/popper.min.js HTTP/1.1" 200 7523 "https://chimitheque.XXX.XXX.fr/chimitheque/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0" "-"
nginx        | 2023-11-02T09:28:35.517989810Z 1XX.2XX.1XX.2XX - - [02/Nov/2023:09:28:35 +0000] "GET /chimitheque/static/js/bootstrap.min.js HTTP/1.1" 200 14898 "https://chimitheque.XXX.XXX.fr/chimitheque/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0" "-"
nginx        | 2023-11-02T09:28:35.522553730Z 1XX.2XX.1XX.2XX - - [02/Nov/2023:09:28:35 +0000] "GET /chimitheque/static/css/animate.min.css HTTP/1.1" 200 5286 "https://chimitheque.XXX.XXX.fr/chimitheque/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0" "-"
nginx        | 2023-11-02T09:28:35.523763728Z 1XX.2XX.1XX.2XX - - [02/Nov/2023:09:28:35 +0000] "GET /chimitheque/static/js/wasm_exec.js HTTP/1.1" 200 4285 "https://chimitheque.XXX.XXX.fr/chimitheque/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0" "-"
nginx        | 2023-11-02T09:28:35.526035002Z 1XX.2XX.1XX.2XX - - [02/Nov/2023:09:28:35 +0000] "GET /chimitheque/static/js/print.js HTTP/1.1" 200 8968 "https://chimitheque.XXX.XXX.fr/chimitheque/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0" "-"
nginx        | 2023-11-02T09:28:35.527013379Z 1XX.2XX.1XX.2XX - - [02/Nov/2023:09:28:35 +0000] "GET /chimitheque/static/js/qr-scanner.umd.min.js HTTP/1.1" 200 3522 "https://chimitheque.XXX.XXX.fr/chimitheque/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0" "-"
nginx        | 2023-11-02T09:28:35.529876002Z 1XX.2XX.1XX.2XX - - [02/Nov/2023:09:28:35 +0000] "GET /chimitheque/static/js/pako.min.js HTTP/1.1" 200 13922 "https://chimitheque.XXX.XXX.fr/chimitheque/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0" "-"
nginx        | 2023-11-02T09:28:35.595644907Z 1XX.2XX.1XX.2XX - - [02/Nov/2023:09:28:35 +0000] "GET /chimitheque/static/img/web-assembly-logo-black.svg HTTP/1.1" 200 1553 "https://chimitheque.XXX.XXX.fr/chimitheque/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0" "-"
nginx        | 2023-11-02T09:28:35.627743626Z 2023/11/02 09:28:35 [warn] 36#36: *9 an upstream response is buffered to a temporary file /var/cache/nginx/proxy_temp/1/00/0000000001 while reading upstream, client: 1XX.2XX.1XX.2XX, server: chimitheque.XXX.XXX.fr, request: "GET /chimitheque/static/fonts/materialdesignicons-webfont.woff2?v=6.5.95 HTTP/1.1", upstream: "http://192.168.224.3:8081/static/fonts/materialdesignicons-webfont.woff2?v=6.5.95", host: "chimitheque.XXX.XXX.fr", referrer: "https://chimitheque.XXX.XXX.fr/chimitheque/static/css/materialdesignicons.min.css"
nginx        | 2023-11-02T09:28:35.629978126Z 1XX.2XX.1XX.2XX - - [02/Nov/2023:09:28:35 +0000] "GET /chimitheque/static/fonts/materialdesignicons-webfont.woff2?v=6.5.95 HTTP/1.1" 200 361384 "https://chimitheque.XXX.XXX.fr/chimitheque/static/css/materialdesignicons.min.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0" "-"
nginx        | 2023-11-02T09:28:35.632323621Z 1XX.2XX.1XX.2XX - - [02/Nov/2023:09:28:35 +0000] "GET /chimitheque/static/fonts/B612-Regular.ttf HTTP/1.1" 200 153192 "https://chimitheque.XXX.XXX.fr/chimitheque/static/css/chimitheque.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0" "-"
nginx        | 2023-11-02T09:28:35.698842941Z 1XX.2XX.1XX.2XX - - [02/Nov/2023:09:28:35 +0000] "GET /chimitheque/static/img/favicon.ico HTTP/1.1" 200 1150 "https://chimitheque.XXX.XXX.fr/chimitheque/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0" "-"
nginx        | 2023-11-02T09:28:35.715502386Z 2023/11/02 09:28:35 [warn] 36#36: *9 an upstream response is buffered to a temporary file /var/cache/nginx/proxy_temp/2/00/0000000002 while reading upstream, client: 1XX.2XX.1XX.2XX, server: chimitheque.XXX.XXX.fr, request: "GET /chimitheque/wasm/wasm.gz HTTP/1.1", upstream: "http://192.168.224.3:8081/wasm/wasm.gz", host: "chimitheque.XXX.XXX.fr", referrer: "https://chimitheque.XXX.XXX.fr/chimitheque/"
nginx        | 2023-11-02T09:28:35.725020494Z 1XX.2XX.1XX.2XX - - [02/Nov/2023:09:28:35 +0000] "GET /chimitheque/wasm/wasm.gz HTTP/1.1" 200 3106909 "https://chimitheque.XXX.XXX.fr/chimitheque/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0" "-"
nginx        | 2023-11-02T09:28:36.341789477Z 1XX.2XX.1XX.2XX - - [02/Nov/2023:09:28:36 +0000] "GET /chimitheque/login HTTP/1.1" 200 865 "https://chimitheque.XXX.XXX.fr/chimitheque/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0" "-"
nginx        | 2023-11-02T09:28:36.360988751Z 1XX.2XX.1XX.2XX - - [02/Nov/2023:09:28:36 +0000] "GET /chimitheque/static/img/logo_chimitheque_small.png HTTP/1.1" 200 3751 "https://chimitheque.XXX.XXX.fr/chimitheque/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0" "-"
nginx        | 2023-11-02T09:28:36.361714865Z 1XX.2XX.1XX.2XX - - [02/Nov/2023:09:28:36 +0000] "GET /chimitheque/static/img/forkme_right_darkblue_121621.png HTTP/1.1" 200 7791 "https://chimitheque.XXX.XXX.fr/chimitheque/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0" "-"
nginx        | 2023-11-02T09:28:36.391264596Z 1XX.2XX.1XX.2XX - - [02/Nov/2023:09:28:36 +0000] "GET /chimitheque/welcomeannounce HTTP/1.1" 200 77 "https://chimitheque.XXX.XXX.fr/chimitheque/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0" "-"
nginx        | 2023-11-02T09:28:41.784990286Z 1XX.2XX.1XX.6XX - - [02/Nov/2023:09:28:41 +0000] "GET / HTTP/1.1" 404 154 "-" "check_http/v2.1.2 (nagios-plugins 2.1.2)" "-"
nginx        | 2023-11-02T09:28:41.784946447Z 2023/11/02 09:28:41 [error] 36#36: *41 "/etc/nginx/html/index.html" is not found (2: No such file or directory), client: 1XX.2XX.1XX.6XX, server: chimitheque.XXX.XXX.fr, request: "GET / HTTP/1.1", host: "staccato.XXX.XXX.fr"
chimitheque  | 2023-11-02T09:28:47.445758252Z time="2023-11-02T09:28:47Z" level=error msg="LDAP Result Code 201 \"Filter Compile Error\": ldap: filter does not start with an '('"
chimitheque  | 2023-11-02T09:28:47.445816964Z time="2023-11-02T09:28:47Z" level=error msg="LDAP user bind error-LDAP Result Code 201 \"Filter Compile Error\": ldap: filter does not start with an '('"
chimitheque  | 2023-11-02T09:28:47.445830436Z time="2023-11-02T09:28:47Z" level=error msg="LDAP Result Code 201 \"Filter Compile Error\": ldap: filter does not start with an '(' LDAP user bind error"
chimitheque  | 2023-11-02T09:28:47.445840303Z 2023/11/02 09:28:47 http: superfluous response.WriteHeader call from main.buildEndpoints.(*Env).AppMiddleware.func4 (middleware.go:40)
nginx        | 2023-11-02T09:28:47.445725476Z 1XX.2XX.1XX.2XX - - [02/Nov/2023:09:28:47 +0000] "POST /chimitheque/get-token HTTP/1.1" 500 212 "https://chimitheque.XXX.XXX.fr/chimitheque/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0" "-"
`

**Comment by tbellembois** [comment]
Après plusieurs tests voici la syntaxe exacte à respecter dans le `docker-compose.yml` pour les paramètres LDAP: 
```
            - CHIMITHEQUE_LDAPSERVERURL=ldaps://ldapserver.foo.fr/ou=users,dc=foo,dc=fr
            - CHIMITHEQUE_LDAPSERVERUSERNAME=CN=admin,OU=users,OU=local,DC=users,DC=fr
            - CHIMITHEQUE_LDAPSERVERPASSWORD=password
            - CHIMITHEQUE_LDAPUSERSEARCHBASEDN=ou=users,dc=foo,dc=fr
            - CHIMITHEQUE_LDAPGROUPSEARCHBASEDN=ou=users,dc=foo,dc=fr
```

**Comment by tbellembois** [comment]
Je clos cette issue. A noter que la future version de Chimithèque n'embarque plus la connexion LDAP celle ci étant déléguée au fournisseur d'identité openid.
