### ISSUE TITLE
Soucis téléchargement vers 2.0.8

### ISSUE THREAD

**Issue by Oribier** [tbellembois/gochimitheque#97]
Bonjour,

Suite à une demande un collègue, nous aimerions installer chimitheque via docker. Cependant, nous rencontrons un problème.
lorsque nous lançons la commande : "docker-compose up -d', un message nous ait retourné : "ERROR: manifest for tbellembois/gochimitheque:2.0.8 not found: manifest unknown: manifest unknown".

En modifiant dans le fichier docker-compose.yml, l image (en commentant la version prod et en décommandant la version dev), cela fonctionne.
Y-a-t-il un soucis avec l image 2.0.8?

Merci d avance
Olivier

**Comment by tbellembois** [comment]
Bonjour,

oui effectivement le tag 2.0.8 n'a pas été créé. Vous pouvez utiliser le tag "latest" en attendant.
