### ISSUE TITLE
Installation de la version 2.0.8 - bug installation standalone

### ISSUE THREAD

**Issue by GitH49** [tbellembois/gochimitheque#98]
Bonjour,

Lors du lancement de la version 2.0.8, cette erreur s'affiche : 
 gochimitheque[3688]: /usr/local/chimitheque/gochimitheque: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /usr/local/chimitheque/gochimitheque)
gochimitheque[3688]: /usr/local/chimitheque/gochimitheque: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /usr/local/chimitheque/gochimitheque)
gochimitheque[3688]: /usr/local/chimitheque/gochimitheque: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/local/chimitheque/gochimitheque)

Le fichier libc.so.6 est un lien symoblique qui pointe sur  libc-2.31.so. A priori il s'agit de la version 2.31.

Le système tourne sous Ubuntu 20.04.5 LTS

La version 2.0.8 est-elle compatible avec la version 20.04.5 d'Ubuntu ou celle-ci doit être upgradée pour la faire fonctionner ?

Merci.

**Comment by tbellembois** [comment]
Bonjour,

Effectivement il s'agit d'un problème de version de libc. Il faut soit recompiler chimithèque sur votre système ou sinon l'installer sur une version plus récente. Je laisse ouvert le ticket pour fournir une solution plus facile à l'avenir.

**Comment by GitH49** [comment]
J'ai passé l'upgrade en version 22.04 et désormais cette erreur s'affiche : gochimitheque[2813]: flag provided but not defined: -proxyurl
L'option est pourtant bien définie dans le fichier chimitheque.service. Je ne l'ai pas modifié. Les options ont-elles changé ?

**Comment by tbellembois** [comment]
La commande `./gochimitheque --help` vous donne les options possibles. C'est `-appurl` et `-apppath` qu'il faut maintenant renseigner.

**Comment by tbellembois** [comment]
Ce problème est il résolu ?

**Comment by GitH49** [comment]
J'ai configuré l'option -appurl, j'ai maintenant cette erreur :
gochimitheque[2831]: panic: error running the server:listen tcp: address ***.****.****: missing port in address
gochimitheque[2831]: goroutine 1 [running]:
gochimitheque[2831]: main.main()
gochimitheque[2831]: #011/home/thbellem/workspace/workspace_go/src/github.com/tbellembois/gochimitheque/main.go:414 +0x107e

**Comment by GitH49** [comment]
La même que pour l'option -proxyurl de la précédente version : https://domain.fr. Cela ne fonctionne pas non plus si j'ajoute le port, comme l'indique l'erreur. J'ai testé les ports 8081 et 443.

**Comment by GitH49** [comment]
Quels sont les bons ports ?

**Comment by GitH49** [comment]
Est-ce que l'application fonctionne toujours en utilisant la méthode classique ou faut-il obligatoirement passer par docker ?

**Comment by tbellembois** [comment]
Non l'installation classique fonctionne toujours. Cependant dans la future version seule l'installation par Docker sera documentée.

**Comment by tbellembois** [comment]
```
server {
...
add_header Access-Control-Allow-Origin "*"
}
```

devrait résoudre le problème.

**Comment by fred981** [comment]
Bonjour,

je travaille avec GitH49 sur la mise en place du serveur chimitheque.
Le problème qu'il indique n'est pas résolu par l'ajout de la directive que vous indiquez et est plus profond que cela. 
Je m'explique : 
Dans la version précédente de chimitheque l'option -proxyurl permettait de faire tourner le service derrière un reverse proxy. Le service tournait sur le port 8081 de l'interface localhost  et ngnix exposait le port 443 et redirigeait le trafic en ajoutant une couche ssl.
Dans la nouvelle version, l'option -appurl indique le nom DNS et le port surlequel écoute le service, ce qui est très différent. Si l'on indique localhost:8081 et qu'on utilise nginx en reverse proxy, les pages générées comportent des références à l'URL locahost:8081 qui est inatteignable de l'extèrieur. Si l'on indique <nom_du_serveur>:8081 alors il n'est plus possible d'utiliser nginx en frontal.
Nous avons essayé de trouver des solutions de contournements  déclarant que l'IP de nom_du_serveur pointait vers 127.0.0.1 et en utilisation du pre-routing iptables  mais cela nous mène à des problèmes COR diffèrents selon les ressources appelés (l'utilisation de add_header produit parfois des entêtes multiples dans la réponse).

Soit il y a une incompréhension de notre part sur l'option -appurl soit il n'est plus possible de faire tourner le service derrière un reverse proxy.

Merci.

**Comment by tbellembois** [comment]
Bonjour,

Je crois que vous avez effectivement trouvé un bug.
Pouvez vous faire ce test :
- laisser -appurl avec l'adresse finale de chimithèque, https://chimitheque.mon.domaine.fr
- mettre -dockerport à 8081 (ou autre port de votre choix), même avec l'installation sans Docker celà va forcer le daemon à écoute sur le port 8081 (adresse: 0.0.0.0)

Configurez bien votre proxy pour rediriger vers le port 8081 de votre machine.

Dites moi si ce contournement fonctionne. Je ferai le correctif ensuite.

**Comment by GitH49** [comment]
Cela fonctionne. Nous vous remercions.

**Comment by tbellembois** [comment]
Je clos cette ancienne issue.
